/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Gambling__factory } from "./Gambling__factory";
export { IERC20__factory } from "./IERC20__factory";
