// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Gambling$Type } from "./Gambling";
import { IERC20$Type } from "./IERC20";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Gambling"]: Gambling$Type;
    ["IERC20"]: IERC20$Type;
    ["contracts/Gambling.sol:Gambling"]: Gambling$Type;
    ["contracts/Gambling.sol:IERC20"]: IERC20$Type;
  }

  interface ContractTypesMap {
    ["Gambling"]: GetContractReturnType<Gambling$Type["abi"]>;
    ["IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
    ["contracts/Gambling.sol:Gambling"]: GetContractReturnType<Gambling$Type["abi"]>;
    ["contracts/Gambling.sol:IERC20"]: GetContractReturnType<IERC20$Type["abi"]>;
  }
}
