/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as gamblingSol from "./Gambling.sol";
export type { gamblingSol };
export type { Hetic } from "./Hetic";
