/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as gamblingSol from "./Gambling.sol";
export { Hetic__factory } from "./Hetic__factory";
export { Lock__factory } from "./Lock__factory";
